on:
  release:
    tags:
      - "*"

jobs:
  Publish:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - run: yarn install
      - name: Publish
        if: success() && startsWith(github.ref, 'refs/tags/') && matrix.os == 'ubuntu-latest'
        run: yarn run deploy
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
